ASide:
  - Room: "a-00"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "a-00b"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "a-00c"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "a-00d"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "a-00x"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
  - Room: "a-01"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 1
      Kind: inout
  - Room: "a-02"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
  - Room: "a-03"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "a-04"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
  - Room: "a-05"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Up
      Idx: 1
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "a-06"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "a-07"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
  - Room: "a-08"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 1
      Kind: inout
    - Side: Right
      Idx: 2
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
  - Room: "a-09"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "a-10"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "a-11"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
  - Room: "a-12"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 1
      Kind: inout
    - Side: Left
      Idx: 2
      Kind: inout
  - Room: "a-13"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "a-14"
    Holes:
    - Side: Down
      Idx: 0
      Kind: inout
  - Room: "a-15"
    Holes:
    - Side: Down
      Idx: 0
      Kind: inout
  - Room: "b-00"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "b-01"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Up
      Idx: 1
      Kind: inout
    - Side: Up
      Idx: 2
      Kind: inout
    - Side: Up
      Idx: 3
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 1
      Kind: inout
  - Room: "b-01b"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "b-01c"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Up
      Idx: 1
      Kind: inout
  - Room: "b-02"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 1
      Kind: inout
    - Side: Right
      Idx: 2
      Kind: inout
    - Side: Right
      Idx: 3
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 1
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
  - Room: "b-03"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
  - Room: "b-04"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
  - Room: "b-05"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "b-06"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 1
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "b-07"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 1
      Kind: inout
  - Room: "b-08"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "b-09"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 1
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
  - Room: "b-10"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
  - Room: "b-11"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 1
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 1
      Kind: inout
  - Room: "b-12"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Up
      Idx: 1
      Kind: inout
  - Room: "b-13"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 1
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "b-14"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "b-15"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "b-16"
    Holes:
    - Side: Down
      Idx: 0
      Kind: inout
  - Room: "b-17"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 1
      Kind: inout
  - Room: "b-18"
    Holes:
    - Side: Down
      Idx: 0
      Kind: inout
  - Room: "b-19"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 1
      Kind: inout
  - Room: "b-20"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 1
      Kind: inout
    - Side: Down
      Idx: 2
      Kind: inout
    - Side: Down
      Idx: 3
      Kind: inout
  - Room: "b-21"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
  - Room: "b-22"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "c-00"
    Holes:
    - Side: Right
      Idx: 1
      Kind: inout
  - Room: "c-01"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "c-01b"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "c-01c"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "c-07"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "c-08"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "c-08b"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "c-09"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "c-10"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "c-11"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "c-12"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "c-13"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "d-00"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
  - Room: "d-01"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 1
      Kind: inout
    - Side: Right
      Idx: 2
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 1
      Kind: inout
    - Side: Left
      Idx: 2
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 1
      Kind: inout
    - Side: Down
      Idx: 2
      Kind: inout
  - Room: "d-02"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "d-03"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
  - Room: "d-04"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 1
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 1
      Kind: inout
  - Room: "d-05"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
  - Room: "d-06"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Up
      Idx: 1
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
  - Room: "d-07"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "d-09"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
  - Room: "d-10"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "d-13"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Up
      Idx: 1
      Kind: inout
  - Room: "d-15"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 1
      Kind: inout
    - Side: Left
      Idx: 2
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 1
      Kind: inout
  - Room: "d-19"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Up
      Idx: 1
      Kind: inout
  - Room: "d-19b"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 1
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 1
      Kind: inout
  - Room: "d-20"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
  - Room: "e-00"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
  - Room: "e-01"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "e-02"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "e-03"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "e-04"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "e-05"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "e-06"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "e-07"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "e-08"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "e-09"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "e-10"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "e-11"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "void"
    Holes:

BSide:
  - Room: "a-00"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "a-01"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "a-02"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "b-00"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
  - Room: "b-01"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "b-02"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 1
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 1
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
  - Room: "b-03"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
  - Room: "b-04"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
  - Room: "b-05"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 1
      Kind: inout
  - Room: "b-06"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
  - Room: "b-07"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "b-08"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 1
      Kind: inout
  - Room: "b-09"
    Holes:
    - Side: Down
      Idx: 0
      Kind: inout
  - Room: "c-00"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
  - Room: "c-01"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "c-02"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "c-03"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "c-04"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "d-00"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
  - Room: "d-01"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "d-02"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "d-03"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "d-04"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "d-05"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "start"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout

CSide:
  - Room: "00"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
  - Room: "01"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "02"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
