ASide:
  - Room: "00"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "01"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "02"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "0x"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
  - Room: "a-00"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "a-01"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "a-02"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "a-03"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: None
    - Side: Left
      Idx: 1
      Kind: None
    - Side: Right
      Idx: 0
      Kind: None
    - Side: Right
      Idx: 1
      Kind: None
  - Room: "b-00"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
  - Room: "b-01"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "b-02"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "b-03"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "b-04"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Up
      Idx: 1
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "b-05"
    Holes:
    - Side: Down
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 1
      Kind: inout
  - Room: "b-06"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
  - Room: "b-07"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
  - Room: "b-07b"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
  - Room: "c-00"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
  - Room: "c-00b"
    Holes:
    - Side: Down
      Idx: 0
      Kind: inout
  - Room: "c-01"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "c-02"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "c-03"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Up
      Idx: 1
      Kind: inout
    - Side: Up
      Idx: 2
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "c-03b"
    Holes:
    - Side: Down
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 1
      Kind: inout
    - Side: Down
      Idx: 2
      Kind: inout
  - Room: "c-04"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "d-00"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "d-01"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: None
    - Side: Left
      Idx: 1
      Kind: None
    - Side: Right
      Idx: 0
      Kind: None
  - Room: "d-02"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
  - Room: "d-03"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
  - Room: "d-04"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
  - Room: "d-05"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
  - Room: "d-06"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
  - Room: "d-07"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
  - Room: "d-08"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
  - Room: "d-09"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "d-10"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "d-10b"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "d-10c"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "d-11"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "space"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Up
      Idx: 0
      Kind: None
    - Side: Down
      Idx: 0
      Kind: None

BSide:
  - Room: "00"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
  - Room: "01"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "a-00"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "a-01"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "a-02"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "a-03"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
  - Room: "a-04"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "a-05"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "b-00"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
  - Room: "b-01"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "b-02"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "b-03"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "b-04"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "b-05"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "c-01"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "c-02"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
  - Room: "c-03"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
  - Room: "c-04"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
  - Room: "c-05"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
  - Room: "c-06"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "c-07"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "c-08"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "space"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout

CSide:
  - Room: "00"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "01"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "02"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "intro"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
