ASide:
  - Room: "1"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: none
  - Room: "2"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
      ReqBoth:          # both directions dashless require a double jump
        Or:
        - Dashes: one
        - Dashes: zero
          Difficulty: hard
    Tweaks:
    - ID: 7             # shorten jumpthru
      Update:
        X: 16
        Width: 32
  - Room: "3"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
      ReqIn:          # traversing upward dashless requires a double jump
        Or:
        - Dashes: one
        - Dashes: zero
          Difficulty: hard
    Tweaks:
    - ID: 0             # shorten jumpthru
      Update:
        Width: 24
        X: 24
    - Name: "spawn"
      Update:
        Add: true
        X: 264
        Y: 64
  - Room: "4"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
    Tweaks:
    - ID: 0             # shorten jumpthru
      Update:
        Width: 24
        X: 32
  - Room: "3b"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
    Tweaks:
    - ID: 0             # shorten jumpthru
      Update:
        X: 40
        Width: 24
  - Room: "5"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
      ReqOut:
        Dashes: one
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
    Tweaks:
    - ID: 0             # shorten jumpthru
      Update:
        Width: 16
  - Room: "5a"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "5z"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
  - Room: "6"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
      ReqBoth:           # traversing the room dashless requires a corner boost or something?
        Or:
        - Dashes: one
        - Dashes: zero
          Difficulty: expert
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
    Tweaks:
    - ID: 0
      Update:
        Width: 16
        X: 16
    - Name: "spawn"
      X: 16
      Y: 168
      Update:
        X: 24
  - Room: "6z"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    InternalEdges:
    - To: "left"
      ReqBoth:
        Dashes: one
    Subrooms:
    - Room: "left"
      Holes:
      - Side: Up
        Idx: 0
        Kind: inout
      - Side: Left
        Idx: 0
        Kind: inout
  - Room: "6zb"
    Holes:
    - Side: Up
      Idx: 0
      Kind: in
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Up
      Idx: 1
      Kind: None
    - Side: Up
      Idx: 2
      Kind: None
    - Side: Up
      Idx: 3
      Kind: None
    - Side: Up
      Idx: 4
      Kind: None
  - Room: "7zb"
    Holes:
    - Side: Down
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 5
      Kind: inout
    - Side: Down
      Idx: 1
      Kind: None
    - Side: Down
      Idx: 2
      Kind: None
    - Side: Down
      Idx: 3
      Kind: None
    - Side: Down
      Idx: 4
      Kind: None
  - Room: "6a"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
      ReqIn:                    # coffee shop jump
        Or:
        - Dashes: one
        - Dashes: zero
          Difficulty: expert
  - Room: "6b"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 1
      Kind: inout
  - Room: "s0"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "s1"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
  - Room: "6c"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
      ReqOut:
        Dashes: one
    - Side: Left
      Idx: 1
      Kind: inout
    Tweaks:
    - Name: "spawn"
      Update:
        Add: true
        X: 280
        Y: 40
  - Room: "7"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
    Tweaks:
    - ID: 0
      Update:
        Width: 16
        X: 64
    - Name: "spawn"
      X: 64
      Update:
        X: 72
  - Room: "7z"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
      ReqOut:
        Dashes: one
    - Side: Right
      Idx: 0
      Kind: inout
  - Room: "8z"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
  - Room: "8zb"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
      ReqOut:
        Or:
        - Dashes: one
        - Dashes: zero
          Difficulty: hard
  - Room: "8"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: in
    - Side: Down
      Idx: 0
      Kind: inout
      ReqIn:                    # fuck this jump in particular
        Or:
        - Dashes: one
        - Dashes: zero
          Difficulty: expert
      ReqOut:
        Dashes: one             # can't traverse backwards without a dash
    - Side: Down
      Idx: 1
      Kind: inout
      ReqOut:
        Dashes: one
    - Side: Down
      Idx: 2
      Kind: in
    Tweaks:
    - ID: 0
      Update:
        Width: 16
        X: 24
    - Name: "spawn"
      X: 24
      Update:
        X: 32
  - Room: "7a"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Up
      Idx: 1
      Kind: inout
  - Room: "9z"
    Holes:
    - Side: Down
      Idx: 0
      Kind: inout
  - Room: "8b"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
      ReqIn:
        Or:
        - Difficulty: hard
          Dashes: zero
        - Dashes: one
    - Side: Left
      Idx: 0
      Kind: inout
    Tweaks:
    - Name: "spawn"
      Update:
        Add: true
        X: 280
        Y: 32
  - Room: "9"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
      ReqOut:
        Or:
        - Dashes: one
        - Dashes: zero
          Difficulty: expert
    Tweaks:
    - ID: 0
      Update:
        Width: 24
  - Room: "9b"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    InternalEdges:
    - To: "right"
      ReqIn:
        Dashes: one
      ReqOut:
        Dashes: zero
    Subrooms:
    - Room: "right"
      Holes:
      - Side: Up
        Idx: 1
        Kind: inout
      - Side: Right
        Idx: 0
        Kind: inout
  - Room: "9c"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "10"
    Holes:
    - Side: Up
      Idx: 0
      Kind: out
    - Side: Up
      Idx: 1
      Kind: in
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
  - Room: "10z"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "10zb"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
  - Room: "10a"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
      ReqBoth:
        Or:
        - Dashes: one
        - Dashes: zero
          Difficulty: expert
    - Side: Down
      Idx: 0
      Kind: inout
    Tweaks:
    - Name: "spawn"
      Update:
        Add: true
        X: 56
        Y: 96
  - Room: "11"
    Holes:
    - Side: Down
      Idx: 2
      Kind: inout
    InternalEdges:
    - To: "exit"
      ReqBoth:
        Or:
        - Dashes: one
        - Dashes: zero
          Difficulty: expert
    Subrooms:
    - Room: "exit"
      Holes:
      - Side: Up
        Idx: 0
        Kind: inout
    - Room: "secret"
      Holes:
      - Side: Left
        Idx: 0
        Kind: inout
        ReqOut:
          Dashes: one
      - Side: Down
        Idx: 0
        Kind: inout
      - Side: Down
        Idx: 1
        Kind: inout
        ReqIn:
          Or:
          - Dashes: one
          - Dashes: zero
            Difficulty: expert
        ReqOut:
          Dashes: one
    Tweaks:
    - ID: 11
      Update:
        Width: 16
    - ID: 0
      Update:
        Width: 8
    - Name: "spawn"
      Update:
        Add: true
        X: 88
        Y: 80
    - Name: "spawn"
      X: 48
      Update:
        X: 40
    - Name: "spawn"
      X: 368
      Update:
        X: 360
  - Room: "11z"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
  - Room: "12"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
      ReqBoth:
        Or:
        - Dashes: one
        - Dashes: zero
          Difficulty: expert
    - Side: Left
      Idx: 0
      Kind: inout
      ReqBoth:
        Or:
        - Dashes: one
        - Dashes: zero
          Difficulty: expert
    - Side: Down
      Idx: 0
      Kind: inout
      ReqBoth:
        Or:
        - Dashes: one
        - Dashes: zero
          Difficulty: expert
    Tweaks:
    - ID: 0
      Update:
        X: 40
        Width: 16
    - Name: "spawn"
      X: 32
      Y: 216
      Update:
        X: 40
  - Room: "12z"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
  - Room: "12a"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
      ReqOut:
        Or:
        - Dashes: one
        - Dashes: zero
          Difficulty: expert
    - Side: Left
      Idx: 0
      Kind: inout
    Tweaks:
    - Name: "spawn"
      Update:
        Add: true
        X: 80
        Y: 32
  - Room: "end"
    Holes:
    - Side: Down
      Idx: 0
      Kind: in
    End: true

BSide:
  - Room: "00"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
  - Room: "01"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: in
  - Room: "02"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: in
  - Room: "02b"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: in
  - Room: "03"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: in
  - Room: "04"
    Holes:
    - Side: Up
      Idx: 1
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "05"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: in
  - Room: "05b"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: in
  - Room: "06"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: in
    - Side: Left
      Idx: 0
      Kind: None
  - Room: "07"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "08"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: in
  - Room: "08b"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: in
  - Room: "09"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: in
  - Room: "10"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "11"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "end"
    Holes:
    - Side: Down
      Idx: 0
      Kind: in
    - Side: Down
      Idx: 1
      Kind: None
    - Side: Down
      Idx: 2
      Kind: None
    - Side: Down
      Idx: 3
      Kind: None
    - Side: Down
      Idx: 4
      Kind: None
    - Side: Up
      Idx: 1
      Kind: None
    - Side: Up
      Idx: 2
      Kind: None
    - Side: Up
      Idx: 3
      Kind: None
    - Side: Up
      Idx: 4
      Kind: None
    - Side: Right
      Idx: 0
      Kind: None
    - Side: Right
      Idx: 1
      Kind: None
    - Side: Right
      Idx: 2
      Kind: None
    - Side: Right
      Idx: 3
      Kind: None

CSide:
  - Room: "00"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: None
    - Side: Down
      Idx: 1
      Kind: None
    - Side: Down
      Idx: 2
      Kind: None
    - Side: Down
      Idx: 3
      Kind: None
    - Side: Down
      Idx: 4
      Kind: None
    - Side: Down
      Idx: 5
      Kind: None
    - Side: Down
      Idx: 6
      Kind: None
    - Side: Down
      Idx: 7
      Kind: None
    - Side: Down
      Idx: 8
      Kind: None
    - Side: Down
      Idx: 9
      Kind: None
    - Side: Down
      Idx: 10
      Kind: None
    - Side: Down
      Idx: 11
      Kind: None
    - Side: Down
      Idx: 12
      Kind: None
    - Side: Up
      Idx: 1
      Kind: None
    - Side: Up
      Idx: 2
      Kind: None
    - Side: Up
      Idx: 3
      Kind: None
    - Side: Up
      Idx: 4
      Kind: None
    - Side: Up
      Idx: 5
      Kind: None
    - Side: Up
      Idx: 6
      Kind: None
  - Room: "01"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "02"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Up
      Idx: 0
      Kind: None
    - Side: Up
      Idx: 1
      Kind: None
    - Side: Up
      Idx: 2
      Kind: None
    - Side: Up
      Idx: 3
      Kind: None
    - Side: Up
      Idx: 4
      Kind: None
    - Side: Up
      Idx: 5
      Kind: None
    - Side: Up
      Idx: 6
      Kind: None
    - Side: Up
      Idx: 7
      Kind: None
    - Side: Up
      Idx: 8
      Kind: None
    - Side: Up
      Idx: 9
      Kind: None
    - Side: Up
      Idx: 10
      Kind: None
    - Side: Up
      Idx: 11
      Kind: None
    - Side: Down
      Idx: 0
      Kind: None
    - Side: Down
      Idx: 1
      Kind: None
    - Side: Down
      Idx: 2
      Kind: None
    - Side: Down
      Idx: 3
      Kind: None
    - Side: Down
      Idx: 4
      Kind: None
    - Side: Down
      Idx: 5
      Kind: None
    - Side: Down
      Idx: 6
      Kind: inout   # shhhh ;)
