ASide:
  - Room: "start"
    Holes:
    - Side: Up
      Idx: 0
      Kind: in
    - Side: Right
      Idx: 0
      Kind: inout
  - Room: "s0"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
    InternalEdges:
    - Split: TopToBottom
      ReqOut:
        Dashes: zero
      ReqIn:
        Or:
        - Dashes: one
        - Dashes: zero
          Difficulty: hard
  - Room: "s1" #questionable
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: out
    InternalEdges:
    - Split: TopToBottom
      ReqOut:
        Dashes: zero
      ReqIn:
        Dashes: one
  - Room: "s2"
    Holes:
    - Side: Down
      Idx: 0
      Kind: inout
    End: true
  - Room: "0"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
      ReqOut:
        Dashes: one
    - Side: Right
      Idx: 0
      Kind: inout
      ReqBoth:
        Dashes: one
    - Side: Right
      Idx: 1
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "1"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 1
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
    Subrooms:
    - Room: "berry"
      Holes:
      - Side: Left
        Idx: 0
        Kind: inout
      InternalEdges:
      - Collectable: 0
        ReqBoth:
          Dashes: one
  - Room: "2"
    Holes:
    - Side: Up
      Idx: 0
      Kind: in
    - Side: Right
      Idx: 0
      Kind: inout
    Subrooms:
    - Room: "peek"
      Holes:
      - Side: Left
        Idx: 0
        Kind: inout
  - Room: "3x"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
    InternalEdges:
    - Split: BottomToTop
      ReqBoth:
        Dashes: one
  - Room: "3"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: in
    InternalEdges:
    - Split: BottomToTop
      ReqBoth:
        Dashes: one
  - Room: "4"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: in
    InternalEdges:
    - Split: BottomToTop
      ReqBoth:
        Dashes: one
  - Room: "5"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: in
    InternalEdges:
    - Split: BottomToTop
      ReqBoth:
        Dashes: one
  - Room: "6"
    Holes:
    - Side: Up
      Idx: 0
      Kind: out
    - Side: Down
      Idx: 0
      Kind: in
    InternalEdges:
    - Split: BottomToTop
      ReqBoth:
        Dashes: one
  - Room: "7"
    Holes:
    - Side: Up
      Idx: 0
      Kind: out
    - Side: Down
      Idx: 0
      Kind: in
    InternalEdges:
    - Split: BottomToTop
      ReqBoth:
        Dashes: one
  - Room: "8"
    Holes:
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Down
      Idx: 1
      Kind: in
    - Side: Left
      Idx: 0
      Kind: None
    - Side: Down
      Idx: 0
      Kind: None
    InternalEdges:
    - Split: BottomToTop
      ReqBoth:
        Dashes: one
  - Room: "9"
    Holes:
    - Side: Up
      Idx: 0
      Kind: in
    - Side: Up
      Idx: 1
      Kind: inout
      ReqOut:
        Dashes: one
    - Side: Up
      Idx: 2
      Kind: none
    - Side: Left
      Idx: 0
      Kind: inout
      ReqOut:
        Dashes: one
    - Side: Down
      Idx: 1
      Kind: out
      ReqOut:
        Dashes: one
    Tweaks:
    - Name: "spawn"
      Update:
        Add: true
        X: 208
        Y: 24
    - ID: 33
      Update:
        Remove: true
  - Room: "9b"
    Holes:
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: inout
    - Side: Down
      Idx: 2
      Kind: in
    - Side: Down
      Idx: 3
      Kind: none
  - Room: "10"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
  - Room: "11"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "12b"
    Holes:
    - Side: Up
      Idx: 1
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
      ReqBoth:
        Dashes: one
    - Side: Left
      Idx: 0
      Kind: inout
      ReqBoth:
        Dashes: one
    - Side: Down
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
    - Side: Down
      Idx: 1
      Kind: in
  - Room: "12c"
    Holes:
    - Side: Down
      Idx: 0
      Kind: inout
  - Room: "12"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "12d"
    Holes:
    - Side: Up
      Idx: 0
      Kind: in
    - Side: Up
      Idx: 1
      Kind: inout
  - Room: "13"
    Holes:
    - Side: Left
      Idx: 0
      Kind: None
    # TODO: Warp
  - Room: "d0"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
      ReqBoth:
        Dashes: one
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 1
      Kind: inout
    InternalEdges:
    - To: "lower"
      ReqOut:
        Dashes: zero
    - To: "middle_right"
      ReqBoth:
        Dashes: one
    Subrooms:
    - Room: "lower"
      Holes:
      - Side: Down
        Idx: 0
        Kind: inout
        ReqBoth:
          Dashes: one
      - Side: Left
        Idx: 2
        Kind: inout
      - Side: Right
        Idx: 2
        Kind: inout
        ReqOut:
          Dashes: one
      InternalEdges:
      - To: "middle_right"
        ReqOut:
          Dashes: one
        ReqIn:
          Dashes: zero
    - Room: "middle_right"
      Holes:
      - Side: Right
        Idx: 1
        Kind: inout
  - Room: "d1"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 1
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
      ReqOut:
        Dashes: one
  - Room: "d2"
    Holes:
    - Side: Up
      Idx: 0
      Kind: in
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "d3"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 1
      Kind: inout
    InternalEdges:
    - Split: TopToBottom
      ReqBoth:
        Dashes: one
    Subrooms:
    - Room: "berry"
      Holes:
      - Side: Left
        Idx: 2
        Kind: inout
  - Room: "d4"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
  - Room: "d5"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "d6"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
    InternalEdges:
    - Split: LeftToRight
      ReqIn:
        Dashes: one
        Difficulty: hard
  - Room: "d7"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    InternalEdges:
    - Split: LeftToRight
      ReqBoth:
        Dashes: one
  - Room: "d8"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    InternalEdges:
    - To: "right"
      ReqOut:
        Or:
        - Dashes: one
        - Dashes: zero
          Difficulty: hard
      ReqIn:
        Or:
        - Dashes: one
        - Dashes: zero
          Difficulty: expert
    Subrooms:
    - Room: "right"
      Holes:
      - Side: Right
        Idx: 0
        Kind: out
      - Side: Right
        Idx: 1
        Kind: inout
  - Room: "d9"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
  - Room: "end_0"
    Holes:
    - Side: Up
      Idx: 0
      Kind: in 
    - Side: Up
      Idx: 1
      Kind: in #the two ins are accessible from each other technically
    - Side: Right
      Idx: 0
      Kind: inout
  - Room: "end_1"
    Holes:
    - Side: Up
      Idx: 0
      Kind: in
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 1
      Kind: inout
    - Side: Right
      Idx: 2
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "end_2"
    Holes:
    - Side: Right
      Idx: 1
      Kind: inout
    - Side: Left
      Idx: 2
      Kind: inout
    Subrooms:
    - Room: "theo"
      Holes:
      - Side: Left
        Idx: 0
        Kind: inout
      - Side: Left
        Idx: 1
        Kind: inout
      - Side: Right
        Idx: 0
        Kind: inout
  - Room: "end_3"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 1
      Kind: inout
  - Room: "end_3b"
    Holes:
    - Side: Up
      Idx: 1
      Kind: inout
      ReqOut:
        Dashes: one
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "end_3c"
    Holes:
    - Side: Down
      Idx: 0
      Kind: inout
  - Room: "end_3cb"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
    InternalEdges:
    - Split: BottomToTop
      ReqOut:
        Dashes: one
  - Room: "end_4"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "end_5"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "end_6"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    End: true
  - Room: "end_s0"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
      ReqOut:
        Dashes: one
        Difficulty: hard
    - Side: Up
      Idx: 1
      Kind: inout
    - Side: Up
      Idx: 2
      Kind: inout
      ReqOut:
        Dashes: one
        Difficulty: hard
    - Side: Down
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 1
      Kind: inout
  - Room: "end_s1"
    Holes:
    - Side: Down
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 1
      Kind: inout
    - Side: Down
      Idx: 2
      Kind: inout

BSide:
  - Room: "start"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: in
  - Room: "00"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
      ReqBoth:
        Dashes: one
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "01"
    Holes:
    - Side: Up
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: None
    - Side: Right
      Idx: 0
      Kind: None
  - Room: "01b"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
    InternalEdges:
    - Split: BottomToTop
      ReqBoth:
        Dashes: one
    Tweaks:
    - ID: 0
      Update:
        Width: 16
    - Name: "spawn"
      Update:
        Add: true
        X: 456
        Y: 32
  - Room: "02b"
    Holes:
    - Side: Up
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
    - Side: Down
      Idx: 0
      Kind: in
  - Room: "02"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
    InternalEdges:
    - Split: BottomToTop
      ReqOut:
        Dashes: one
      ReqIn:
        Dashes: two
    Tweaks:
    - ID: 0
      Update:
        X: 24
        Width: 24
    - Name: "spawn"
      Update:
        Add: true
        X: 880
        Y: 24
  - Room: "03"
    Holes:
    - Side: Up
      Idx: 0
      Kind: out
    - Side: Down
      Idx: 0
      Kind: in
      ReqIn:
        Dashes: one
  - Room: "04"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: in
      ReqIn:
        Dashes: one
  - Room: "05"
    Holes:
    - Side: Up
      Idx: 0
      Kind: out
    - Side: Down
      Idx: 0
      Kind: in
    InternalEdges:
    - Split: BottomToTop
      ReqOut:
        Dashes: one
      ReqIn:
        Dashes: two
    Tweaks:
    - ID: 0
      Update:
        Width: 24
    - Name: "spawn"
      Update:
        Add: true
        X: 296
        Y: 24
  - Room: "06"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
    - Side: Down
      Idx: 0
      Kind: in
  - Room: "07"
    Holes:
    - Side: Up
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "08b"
    Holes:
    - Side: Up
      Idx: 2
      Kind: out
      ReqOut:
        Dashes: one
    - Side: Down
      Idx: 0
      Kind: in
    Tweaks:
    - ID: 12
      Update:
        Y: 16
        Height: 104
  - Room: "08"
    Holes:
    - Side: Up
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
    - Side: Down
      Idx: 0
      Kind: in
  - Room: "09"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
      ReqOut:
        Dashes: one
    - Side: Down
      Idx: 0
      Kind: in
  - Room: "10"
    Holes:
    - Side: Up
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "11"
    Holes:
    - Side: Up
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
    - Side: Down
      Idx: 0
      Kind: in
  - Room: "end"
    Holes:
    - Side: Down
      Idx: 0
      Kind: in
      ReqIn:
        Dashes: one
    - Side: Left
      Idx: 0
      Kind: inout
      ReqIn:
        Dashes: one
    - Side: Right
      Idx: 0
      Kind: inout
      ReqIn:
        Dashes: one
    End: true

CSide:
  - Room: "00"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    InternalEdges:
    - Split: LeftToRight
      ReqBoth:
        Dashes: one
  - Room: "01"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
        Difficulty: hard
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "02"
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
      ReqIn:
        Dashes: one
        Difficulty: hard
    End: true
