ASide:
  - Room: "s0"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 1
      Kind: None
    - Side: Down
      Idx: 0
      Kind: None
  - Room: "s1"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 1
      Kind: inout
    - Side: Right
      Idx: 2
      Kind: None
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 1
      Kind: None
  - Room: "s2"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 1
      Kind: None
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 1
      Kind: inout
    - Side: Left
      Idx: 2
      Kind: none
  - Room: "s3"
    Holes:
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 1
      Kind: out
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 1
      Kind: None
  - Room: "00-a"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "00-b"
    Holes:
    - Side: Up
      Idx: 0
      Kind: None #inaccessible
    - Side: Up
      Idx: 1
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 1
      Kind: None #inaccessible
    - Side: Left
      Idx: 0
      Kind: None #inaccessible
    - Side: Left
      Idx: 1
      Kind: None #inaccessible
  - Room: "00-c"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 1
      Kind: inout
  - Room: "00-d"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
  - Room: "01-b"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 1
      Kind: inout
  - Room: "01-c"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: None
  - Room: "02-a"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: None #TODO key door
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "02-b"
    Holes:
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
  - Room: "02-c"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
  - Room: "02-d"
    Holes:
    - Side: Right
      Idx: 0
      Kind: in
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "03-a"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "03-b"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "04-b"
    Holes:
    - Side: Left
      Idx: 0
      Kind: None
    - Side: Down
      Idx: 0
      Kind: inout
  - Room: "04-c"
    Holes:
    - Side: Up
      Idx: 0
      Kind: None #TODO key door
    - Side: Up
      Idx: 1
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "04-d"
    Holes:
    - Side: Right
      Idx: 0
      Kind: in
    - Side: Left
      Idx: 0
      Kind: out
    - Side: Down
      Idx: 0
      Kind: out
    - Side: Down
      Idx: 1
      Kind: inout
    - Side: Down
      Idx: 2
      Kind: None
    - Side: Down
      Idx: 3
      Kind: None
    - Side: Down
      Idx: 4
      Kind: None
  - Room: "05-a"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "05-c"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
  - Room: "06-a"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "06-b"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: None
  - Room: "06-c"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: in
    - Side: Down
      Idx: 1
      Kind: inout
  - Room: "06-d"
    Holes:
    - Side: Right
      Idx: 0
      Kind: in
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "07-a"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: None #TODO key door
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "07-b"
    Holes:
    - Side: Up
      Idx: 0
      Kind: None
    - Side: Right
      Idx: 0
      Kind: in
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
  - Room: "08-a"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: in
    - Side: Down
      Idx: 0
      Kind: None #TODO clean any -> inout
  - Room: "08-b"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "08-c"
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
    - Side: Down
      Idx: 0
      Kind: out
  - Room: "08-d"
    Holes:
    - Side: Right
      Idx: 0
      Kind: in
    - Side: Left
      Idx: 0
      Kind: out
    - Side: Down
      Idx: 0
      Kind: None
  - Room: "08-x"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Up
      Idx: 1
      Kind: inout
  - Room: "09-b"
    Holes:
    - Side: Up
      Idx: 0
      Kind: None #TODO key door
    - Side: Up
      Idx: 1
      Kind: in
    - Side: Up
      Idx: 2
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 1
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: None #TODO clean any -> in
    - Side: Down
      Idx: 1
      Kind: in
    - Side: Down
      Idx: 2
      Kind: out
  - Room: "09-d"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: in
  - Room: "0x-a"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "0x-b"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 1
      Kind: out
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "10-c"
    Holes:
    - Side: Up
      Idx: 0
      Kind: None #inaccessible
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: None #inaccessible
    - Side: Down
      Idx: 1
      Kind: inout
  - Room: "10-d"
    Holes:
    - Side: Right
      Idx: 0
      Kind: in
    - Side: Down
      Idx: 0
      Kind: out
  - Room: "10-x"
    Holes:
    - Side: Up
      Idx: 0
      Kind: out
    - Side: Up
      Idx: 1
      Kind: None #inaccessible
    - Side: Right
      Idx: 0
      Kind: None #inaccessible
    - Side: Down
      Idx: 0
      Kind: in
  - Room: "10-y"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: in
  - Room: "10-z"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
  - Room: "11-a"
    Holes:
    - Side: Right
      Idx: 0
      Kind: None #inaccessible
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: in
    - Side: Down
      Idx: 1
      Kind: None #inaccessible
  - Room: "11-b"
    Holes:
    - Side: Up
      Idx: 0
      Kind: in
    - Side: Up
      Idx: 1
      Kind: None #TODO clean pink -> inout
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 1
      Kind: None
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "11-c"
    Holes:
    - Side: Right
      Idx: 0
      Kind: None #inaccessible
    - Side: Left
      Idx: 0
      Kind: None #inaccessible
    - Side: Down
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 1
      Kind: in
  - Room: "11-d"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: None
  - Room: "11-x"
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
    - Side: Down
      Idx: 0
      Kind: out
  - Room: "11-y"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
  - Room: "11-z"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "12-b"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 1
      Kind: None
  - Room: "12-c"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "12-d"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: in
  - Room: "12-x"
    Holes:
    - Side: Up
      Idx: 0
      Kind: out
    - Side: Up
      Idx: 1
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: in
  - Room: "12-y"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "13-a"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: None #TODO clean pink -> inout
    - Side: Down
      Idx: 0
      Kind: out
  - Room: "13-b"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
  - Room: "13-x"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: None
    - Side: Down
      Idx: 1
      Kind: None
    - Side: Down
      Idx: 2
      Kind: None
  - Room: "roof00"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
      HighBound: 19
    - Side: Down
      Idx: 0
      Kind: in
  - Room: "roof01"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
      HighBound: 19
    - Side: Left
      Idx: 0
      Kind: in
      HighBound: 19
  - Room: "roof02"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
      HighBound: 19
    - Side: Left
      Idx: 0
      Kind: in
      HighBound: 19
  - Room: "roof03"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Left
      Idx: 0
      Kind: in
      HighBound: 19
  - Room: "roof04"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "roof05"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
      HighBound: 17
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "roof06b"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
      HighBound: 17
    - Side: Left
      Idx: 0
      Kind: in
      HighBound: 17
  - Room: "roof06"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
      HighBound: 10
    - Side: Left
      Idx: 0
      Kind: in
      HighBound: 17
  - Room: "roof07"
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
      HighBound: 10
    - Side: Right
      Idx: 0
      Kind: none
    End: true

BSide:
  - Room: "00"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 1
      Kind: None
  - Room: "01"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 1
      Kind: None
  - Room: "02"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "03"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "04"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: None
  - Room: "05"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "06"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "07"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "08"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "09"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: in
  - Room: "10"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "11"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "12"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "13"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "14"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "15"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "16"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Up
      Idx: 1
      Kind: None
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "17"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
      HighBound: 19
    - Side: Down
      Idx: 0
      Kind: in
    - Side: Down
      Idx: 1
      Kind: None
  - Room: "18"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
      HighBound: 19
    - Side: Left
      Idx: 0
      Kind: in
      HighBound: 19
  - Room: "19"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
      HighBound: 19
    - Side: Left
      Idx: 0
      Kind: in
      HighBound: 19
  - Room: "21"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: in
      HighBound: 19
  - Room: "20"
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
      HighBound: 19
    - Side: Down
      Idx: 0
      Kind: None
    - Side: Down
      Idx: 1
      Kind: out
    - Side: Down
      Idx: 2
      Kind: None
  - Room: "end"
    Holes:
    - Side: Up
      Idx: 0
      Kind: in
    End: true

CSide:
  - Room: "00"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Up
      Idx: 0
      Kind: inout
  - Room: "01"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: in
  - Room: "02-dummy"
    Holes:
    - Side: Up
      Idx: 0
      Kind: None
    - Side: Up
      Idx: 1
      Kind: None
  - Room: "02"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: None
    - Side: Down
      Idx: 1
      Kind: None
    - Side: Down
      Idx: 2
      Kind: None
