ASide:
  - Room: "a-00"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "a-01"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    InternalEdges:
    - Split: LeftToRight
      ReqBoth:
        Dashes: one
  - Room: "a-01x"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: None
  - Room: "a-02"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    InternalEdges:
    - To: "Right"
      ReqOut:
        Dashes: one
      ReqIn:
        Dashes: zero
    Subrooms:
    - Room: "Right"
      Holes:
      - Side: Right
        Idx: 0
        Kind: inout
      InternalEdges:
      - To: "Berry"
        ReqOut:
          Dashes: zero
        ReqIn:
          Dashes: one
    - Room: "Berry"
      Collectables:
      - Idx: 0
  - Room: "a-03"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    InternalEdges:
    - To: "Berry"
      ReqOut:
        Dashes: zero
    - To: "Right"
      ReqOut:
        Dashes: zero
      ReqIn:
        Dashes: one
    Subrooms:
    - Room: "Right"
      Holes:
      - Side: Right
        Idx: 0
        Kind: inout
      InternalEdges:
      - To: "Berry"
        ReqBoth:
          Dashes: zero
    - Room: "Berry"
      Collectables:
      - Idx: 0
  - Room: "a-04"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "a-05"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
  - Room: "a-05x"  # wtf is this room?
    Holes:
    - Side: Up
      Idx: 0
      Kind: None
    - Side: Up
      Idx: 1
      Kind: None
    - Side: Down
      Idx: 0
      Kind: None
      Side: Right
      Idx: 0
      Kind: None
  - Room: "a-06"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    InternalEdges:
    - To: "Right"
      ReqOut:
        Dashes: zero
      ReqIn:
        Or:
        - Dashes: two
        - Dashes: one
          Difficulty: hard
        - Dashes: zero
          Difficulty: expert
    - To: "Berry"
      ReqOut:
        Dashes: one
      ReqIn:
        Dashes: zero  # not quite right but w/e
    Subrooms:
    - Room: "Right"
      Holes:
      - Side: Right
        Idx: 0
        Kind: inout
    - Room: "Berry"
      Collectables:
      - Idx: 0
  - Room: "a-07"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    InternalEdges:
    - To: "Right"
      ReqOut:
        Dashes: one
    Subrooms:
    - Room: "Right"
      Holes:
      - Side: Right
        Idx: 0
        Kind: inout
      InternalEdges:
      - Collectable: 0
        ReqBoth:
          Dashes: one
  - Room: "a-08"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
      ReqOut:
        Dashes: one
    - Side: Left
      Idx: 0
      Kind: inout
      ReqOut:
        Dashes: one
    - Side: Left
      Idx: 1
      Kind: inout
  - Room: "a-10"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    InternalEdges:
    - Collectable: 0
  - Room: "a-09"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: in
    InternalEdges:
    - Collectable: 0
      ReqOut:
        Dashes: one
      ReqIn:
        Dashes: zero
  - Room: "a-11"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
  - Room: "b-00"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
      ReqOut:
        Dashes: one
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Right
      Idx: 1
      Kind: inout
    - Side: Right
      Idx: 2
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 1
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: in
    Tweaks:
    - ID: 4     # change respawn trigger in top right
      Update:
        Remove: true
  - Room: "b-01"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    InternalEdges:
    - To: "berry1"
      ReqBoth:
        Dashes: zero
    - To: "berry2"
      ReqOut:
        Dashes: one
      ReqIn:
        Dashes: zero
    Subrooms:
    - Room: "berry1"
      Collectables:
      - Idx: 0
    - Room: "berry2"
      Collectables:
      - Idx: 1
  - Room: "b-02"
    Holes:
    - Side: Left
      Idx: 1
      Kind: inout
    InternalEdges:
    - Collectable: 1
      ReqBoth:
        Or:
        - Dashes: one
        - Dashes: zero
          Difficulty: hard
    Subrooms:
    - Room: "upper"
      Holes:
      - Side: Up
        Idx: 0
        Kind: inout
      - Side: Right
        Idx: 0
        Kind: inout
        ReqOut:
          Dashes: one
      - Side: Left
        Idx: 0
        Kind: inout
      Collectables:
      - Idx: 0
  - Room: "b-03"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    InternalEdges:
    - Collectable: 0
      ReqBoth:
        Or:
        - Dashes: one
        - Dashes: zero
          Difficulty: hard
  - Room: "b-04"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    Tweaks:
    - ID: 23
      Name: "booster"
      Update:
        Y: 160
    InternalEdges:
    - Split: RightToLeft
      ReqOut:
        Dashes: zero
      ReqIn:
        Dashes: one
    - To: "Berry"
      ReqIn:
        Dashes: zero
    Subrooms:
    - Room: "Berry"
      Holes:
      - Side: Up
        Idx: 0
        Kind: inout
      Collectables:
      - Idx: 0
    Tweaks:
    - ID: 0
      Name: "changeRespawnTrigger"
      Update:
        Remove: true
  - Room: "b-05"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 2
      Kind: inout
    Subrooms:
    - Room: "subroom"
      Holes:
      - Side: Down
        Idx: 0
        Kind: out
      - Side: Down
        Idx: 1
        Kind: in
  - Room: "b-06"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
    InternalEdges:
    - Split: RightToLeft
      ReqOut:
        Or:
        - Dashes: one
        - Dashes: zero
          Difficulty: hard
      ReqIn:
        Dashes: zero
  - Room: "b-07"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
      ReqIn:
        Dashes: one
    - Side: Right
      Idx: 0
      Kind: out
    Tweaks:
    - Name: "spawn"
      X: 24
      Y: 56
      Update:
        Default: true
  - Room: "b-sec"  # TODO: mark the heart as requiring the dashes, not the entrances
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
      ReqBoth:
        Dashes: one
    - Side: Left
      Idx: 0
      Kind: inout
      ReqIn:
        Dashes: one
    End: true
  - Room: "b-secb"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    InternalEdges:
    - Collectable: 0
      ReqBoth:
        Dashes: one
  - Room: "b-08b"  # TODO: add platform/spawn at top
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
  - Room: "b-08"
    Holes:
    - Side: Up
      Idx: 0
      Kind: out
    - Side: Down
      Idx: 0
      Kind: in
  - Room: "c-00"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
      ReqOut:
        Dashes: one
    - Side: Down
      Idx: 0
      Kind: in
    InternalEdges:
    - To: "Right"
      ReqBoth:
        Dashes: one
    - To: "Berry"
      ReqBoth:
        Dashes: one
    Subrooms:
    - Room: "Right"
      Holes:
      - Side: Right
        Idx: 0
        Kind: inout
    - Room: "Berry"
      Collectables:
      - Idx: 0
  - Room: "c-01"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    InternalEdges:
    - Collectable: 0
      ReqBoth:
        Dashes: one
  - Room: "c-02"  # TODO: add platform/spawn at top
    Holes:
    - Side: Up
      Idx: 1
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    InternalEdges:
    - Split: LeftToRight
      ReqOut:
        Dashes: one
      ReqIn:
        Dashes: zero
  - Room: "c-04"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
    - Side: Down
      Idx: 0
      Kind: in
  - Room: "c-05"
    Holes:
    - Side: Up
      Idx: 1
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    InternalEdges:
    - Split: LeftToRight
      ReqBoth:
        Dashes: one
    - To: "Berry"
      ReqBoth:
        Dashes: one
    Subrooms:
    - Room: "Berry"
      Collectables:
      - Idx: 0
  - Room: "c-06"  # TODO: shorten platform and add spawn at top
    Holes:
    - Side: Up
      Idx: 0
      Kind: out
    - Side: Left
      Idx: 0
      Kind: inout
    InternalEdges:
    - To: "Bottom"
      ReqOut:
        Dashes: zero
      ReqIn:
        Dashes: one
    Subrooms:
    - Room: "Bottom"
      Holes:
      - Side: Down
        Idx: 0
        Kind: inout
  - Room: "c-06b"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    InternalEdges:
    - Collectable: 0
      ReqBoth:
        Dashes: one
  - Room: "c-09"  # fwiw this room is doable in two dashes with core mode
    Holes:
    - Side: Up
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
    - Side: Down
      Idx: 0
      Kind: in
  - Room: "c-07"  # TODO: shorten entrance jumpthru
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: in
    InternalEdges:
    - Split: LeftToRight
      ReqOut:
        Dashes: one
      ReqIn:
        Or:
        - Dashes: two
        - Dashes: one
          Difficulty: hard
  - Room: "c-08"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
      ReqOut:
        Dashes: one
    - Side: Right
      Idx: 0
      Kind: inout
      ReqOut:
        Dashes: one
    - Side: Left
      Idx: 0
      Kind: inout
      ReqOut:
        Dashes: one
    InternalEdges:
    - Collectable: 0
      ReqBoth:
        Dashes: one
  - Room: "c-10"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    InternalEdges:
    - Split: BottomToTop
      ReqBoth:
        Dashes: one
    Tweaks:
    - Name: spawn
      Update:
        Add: true
        X: 24
        Y: 24
  - Room: "d-00"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
      ReqOut:
        Or:
        - Dashes: one
        - Dashes: zero
          Difficulty: hard
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: in
    - Side: Down
      Idx: 1
      Kind: in
  - Room: "d-00b"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    InternalEdges:
    - Collectable: 0
      ReqBoth:
        Dashes: one
  - Room: "d-01"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
      ReqOut:
        Dashes: one
    - Side: Left
      Idx: 0
      Kind: inout
    InternalEdges:
    - Collectable: 0
      ReqBoth:
        Dashes: one
  - Room: "d-02"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "d-03"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "d-04"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    InternalEdges:
    - To: "Right"
      ReqOut:
        Or:
        - Dashes: one
        - Dashes: zero
          Difficulty: hard
      ReqIn:
        Dashes: zero
    Subrooms:
    - Room: "Right"
      Holes:
      - Side: Right
        Idx: 0
        Kind: inout
      Collectables:
      - Idx: 0
  - Room: "d-05"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    InternalEdges:
    - Split: LeftToRight
      ReqOut:
        Dashes: one
      ReqIn:
        Dashes: zero
  - Room: "d-06"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    InternalEdges:
    - Split: LeftToRight
      ReqOut:
        Dashes: one
      ReqIn:
        Dashes: zero
  - Room: "d-07"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    InternalEdges:
    - Split: LeftToRight
      ReqOut:
        Dashes: one
      ReqIn:
        Or:
        - Dashes: one
        - Dashes: zero
          Difficulty: hard
  - Room: "d-08"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: up
      Idx: 1
      Kind: none
  - Room: "d-09"        # TODO: Berry
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    InternalEdges:
    - Split: LeftToRight
      ReqOut:
        Dashes: one
      ReqIn:
        Dashes: two
  - Room: "d-10"
    Holes:
    - Side: Left
      Idx: 1
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    End: true

BSide:
  - Room: "a-00"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    InternalEdges:
    - Split: LeftToRight
      ReqBoth:
        Dashes: one
  - Room: "a-01"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    InternalEdges:
    - Split: LeftToRight
      ReqBoth:
        Dashes: one
  - Room: "a-02"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "a-03"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    InternalEdges:
    - Split: LeftToRight
      ReqOut:
        Dashes: one
      ReqIn:
        Dashes: two
        Difficulty: expert
  - Room: "a-04"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    InternalEdges:
    - Split: LeftToRight
      ReqOut:
        Dashes: one
      ReqIn:
        Dashes: two
  - Room: "b-00"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    InternalEdges:
    - Split: LeftToRight
      ReqOut:
        Dashes: one
      ReqIn:
        Dashes: zero
  - Room: "b-01"
    Holes:
    - Side: Up
      Idx: 1
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    InternalEdges:
    - Split: LeftToRight
      ReqOut:
        Dashes: one
      ReqIn:
        Dashes: one
  - Room: "b-02"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: in
      ReqIn:
        Dashes: one
  - Room: "b-03"
    Holes:
    - Side: Up
      Idx: 1
      Kind: out
      ReqOut:
        Dashes: one
    - Side: Down
      Idx: 0
      Kind: in
  - Room: "b-04"  # TODO: shorten jumpthru
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: in
    InternalEdges:
    - Split: LeftToRight
      ReqOut:
        Dashes: one
      ReqIn:
        Or:
        - Dashes: two
        - Dashes: one
          Difficulty: hard
  - Room: "c-00"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "c-01"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    InternalEdges:
    - Split: LeftToRight
      ReqOut:
        Dashes: one
      ReqIn:
        Or:
        - Dashes: two
        - Dashes: one
          Difficulty: hard
  - Room: "c-02"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "c-03"
    Holes:
    - Side: Up
      Idx: 0
      Kind: out
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "c-04"  # TODO: shorten jumpthru
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: in
    InternalEdges:
    - Split: LeftToRight
      ReqOut:
        Dashes: one
      ReqIn:
        Dashes: two
  - Room: "d-00"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "d-01"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "d-02"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
      ReqOut:
        Dashes: one
    - Side: Left
      Idx: 0
      Kind: inout
      ReqOut:
        Or:
        - Dashes: two
        - Dashes: one
          Difficulty: expert
    - Side: Up
      Idx: 0
      Kind: none
    Tweaks:
    - ID: 2
      Name: "exitBlock"
      Update:
        Remove: true
  - Room: "d-03"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "end"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
      ReqIn:
        Dashes: one
    End: true

CSide:
  - Room: "00"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    InternalEdges:
    - Split: LeftToRight
      ReqOut:
        Dashes: one
      ReqIn:
        Dashes: two
        Difficulty: hard
  - Room: "01"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    InternalEdges:
    - Split: LeftToRight
      ReqOut:
        Dashes: one
      ReqIn:
        Dashes: one
        Difficulty: hard
  - Room: "02"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
      ReqIn:
        Or:
        - Dashes: two
        - Dashes: one
          Difficulty: hard
    End: true
