ASide:
  - Room: "start"
    Holes:
  - Room: "00"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
  - Room: "01"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: in
  - Room: "02"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 1
      Kind: none  # TODO: subroom
    - Side: Down
      Idx: 0
      Kind: none
  - Room: "03"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Right
      Idx: 1
      Kind: in
  - Room: "02b"
    Holes:
    - Side: Up
      Idx: 0
      Kind: out
    - Side: Down
      Idx: 0
      Kind: in
  - Room: "04"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 1
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 1
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: in
  - Room: "04b"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "04c"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
  - Room: "04d"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "04e"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
  - Room: "05"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "06"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "07"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 1
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "08a"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "08b"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "09"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 1
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: in
    - Side: Left
      Idx: 1
      Kind: in
  - Room: "10a"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "10b"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "11"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 1
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: in
    - Side: Left
      Idx: 1
      Kind: in
  - Room: "12a"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "12b"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "13"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 1
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: in
    - Side: Left
      Idx: 1
      Kind: in
  - Room: "14a"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "14b"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "15"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 1
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: in
    - Side: Left
      Idx: 1
      Kind: in
  - Room: "16a"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "16b"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "17"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 1
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: in
    - Side: Left
      Idx: 1
      Kind: in
  - Room: "18a"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "18b"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "19"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: in
    - Side: Left
      Idx: 1
      Kind: in
  - Room: "20"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "b-00"
    Holes:
    - Side: Up
      Idx: 1
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "b-00b"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
    - Side: Up
      Idx: 0
      Kind: In
  - Room: "b-00c"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
  - Room: "b-01"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: out
  - Room: "b-02"
    Holes:
    - Side: Up
      Idx: 0
      Kind: in
    - Side: Right
      Idx: 0
      Kind: out
  - Room: "b-02b"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "b-03"
    Holes:
    - Side: Right
      Idx: 0
      Kind: in
    - Side: Left
      Idx: 0
      Kind: out
  - Room: "boss-00"
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
    - Side: Down
      Idx: 0
      Kind: out
  - Room: "boss-01"
    Holes:
    - Side: Up
      Idx: 0
      Kind: in
    - Side: Down
      Idx: 0
      Kind: out
  - Room: "boss-02"
    Holes:
    - Side: Up
      Idx: 0
      Kind: in
    - Side: Down
      Idx: 0
      Kind: out
  - Room: "boss-03"
    Holes:
    - Side: Up
      Idx: 0
      Kind: in
    - Side: Down
      Idx: 0
      Kind: out
  - Room: "boss-04"
    Holes:
    - Side: Up
      Idx: 0
      Kind: in
    - Side: Right
      Idx: 0
      Kind: out
  - Room: "boss-05"
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
    - Side: Down
      Idx: 0
      Kind: out
  - Room: "boss-06"
    Holes:
    - Side: Up
      Idx: 0
      Kind: in
    - Side: Down
      Idx: 0
      Kind: out
  - Room: "boss-07"
    Holes:
    - Side: Up
      Idx: 0
      Kind: in
    - Side: Down
      Idx: 0
      Kind: out
  - Room: "boss-08"
    Holes:
    - Side: Up
      Idx: 0
      Kind: in
    - Side: Down
      Idx: 0
      Kind: out
  - Room: "boss-09"
    Holes:
    - Side: Up
      Idx: 0
      Kind: in
    - Side: Right
      Idx: 0
      Kind: out
  - Room: "boss-10"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "boss-11"
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
    - Side: Down
      Idx: 0
      Kind: out
  - Room: "boss-12"
    Holes:
    - Side: Up
      Idx: 0
      Kind: in
    - Side: Down
      Idx: 0
      Kind: out
  - Room: "boss-13"
    Holes:
    - Side: Up
      Idx: 0
      Kind: in
    - Side: Right
      Idx: 0
      Kind: out
  - Room: "boss-14"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "boss-15"
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
    - Side: Down
      Idx: 0
      Kind: out
  - Room: "boss-16"
    Holes:
    - Side: Up
      Idx: 0
      Kind: in
    - Side: Right
      Idx: 0
      Kind: out
  - Room: "boss-17"
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
    - Side: Down
      Idx: 0
      Kind: out
  - Room: "boss-18"
    Holes:
    - Side: Up
      Idx: 0
      Kind: in
    - Side: Right
      Idx: 0
      Kind: out
  - Room: "boss-19"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "boss-20"
    Holes:
    - Side: Up
      Idx: 0
      Kind: out
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "after-00"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: in
  - Room: "after-01"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: in
  - Room: "after-02"
    Holes:
    - Side: Down
      Idx: 0
      Kind: in
    End: true

BSide:
  - Room: "a-00"
    Holes:
    - Side: Up
      Idx: 0
      Kind: out
  - Room: "a-01"
    Holes:
    - Side: Up
      Idx: 0
      Kind: out
    - Side: Down
      Idx: 0
      Kind: in
  - Room: "a-02"
    Holes:
    - Side: Up
      Idx: 0
      Kind: out
    - Side: Down
      Idx: 0
      Kind: in
  - Room: "a-03"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Down
      Idx: 0
      Kind: in
  - Room: "a-04"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "a-05"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "a-06"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "b-00"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: out
  - Room: "b-01"
    Holes:
    - Side: Up
      Idx: 0
      Kind: in
    - Side: Right
      Idx: 0
      Kind: out
  - Room: "b-02"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "b-03"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "b-04"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "b-05"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "b-06"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "b-07"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "b-08"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "b-10"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "c-00"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Left
      Idx: 0
      Kind: in
    - Side: Down
      Idx: 0
      Kind: None
    - Side: Down
      Idx: 1
      Kind: None
    - Side: Down
      Idx: 2
      Kind: None
    - Side: Down
      Idx: 3
      Kind: None
    - Side: Down
      Idx: 4
      Kind: None
  - Room: "c-01"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "c-02"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "c-03"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "c-04"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "d-00"
    Holes:
    - Side: Up
      Idx: 0
      Kind: out
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "d-01"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Down
      Idx: 0
      Kind: in
  - Room: "d-02"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "d-03"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "d-04"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "d-05"
    Holes:
    - Side: Left
      Idx: 0
      Kind: in

CSide:
  - Room: "00"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "01"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "02"
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
