ASide:
  - Room: "start"  # TODO: warp?
    Holes:
  - Room: "00"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
      ReqOut:
        Dashes: one
  - Room: "01"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
      ReqOut:
        Dashes: one
    - Side: Down
      Idx: 0
      Kind: in
  - Room: "02"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    InternalEdges:
    - Split: BottomToTop
      ReqOut:
        Dashes: zero
      ReqIn:
        Dashes: one
    Subrooms:
    - Room: "lower"
      Holes:
      - Side: Left
        Idx: 1
        Kind: inout
        ReqOut:
          Dashes: one
      - Side: Down
        Idx: 0
        Kind: in
  - Room: "03"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
    - Side: Right
      Idx: 1
      Kind: in
  - Room: "02b"
    Holes:
    - Side: Up
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
    - Side: Down
      Idx: 0
      Kind: in
  - Room: "04"
    Holes:
    - Side: Down
      Idx: 0
      Kind: in
    - Side: Right
      Idx: 1
      Kind: inout
    InternalEdges:
    - To: "cassette"
      ReqOut:
        Dashes: one
      ReqIn:
        Dashes: zero
    - To: "rightexit"
      ReqOut:
        Dashes: one
      ReqIn:
        Dashes: zero
    - To: "heart"
      ReqIn:
        Dashes: zero
    Subrooms:
    - Room: "cassette"
      Holes:
      - Side: Left
        Idx: 0
        Kind: inout
      InternalEdges:
      - To: "heart"
        ReqOut:
          Dashes: zero
          Difficulty: hard
    - Room: "rightexit"
      Holes:
      - Side: Right
        Idx: 0
        Kind: inout
      InternalEdges:
      - To: "heart"
        ReqOut:
          Dashes: one
    - Room: "heart"
      Holes:
      - Side: Left
        Idx: 1
        Kind: inout
  - Room: "04b"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "04c"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
      ReqIn:
        Difficulty: hard
        Dashes: one
    End: true
  - Room: "04d"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "04e"  # TODO: cassette
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
  - Room: "05"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "06"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "07"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 1
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "08a"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    InternalEdges:
    - Split: LeftToRight
      ReqOut:
        Dashes: one
      ReqIn:
        Or:
        - Dashes: two
        - Dashes: one
          Difficulty: hard
  - Room: "08b"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    InternalEdges:
    - Split: LeftToRight
      ReqOut:
        Dashes: one
      ReqIn:
        Dashes: two
  - Room: "09"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 1
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: in
    - Side: Left
      Idx: 1
      Kind: in
  - Room: "10a"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    InternalEdges:
    - Split: LeftToRight
      ReqOut:
        Dashes: one
      ReqIn:
        Or:
        - Dashes: one
        - Dashes: zero
          Difficulty: hard
  - Room: "10b"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "11"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 1
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: in
    - Side: Left
      Idx: 1
      Kind: in
  - Room: "12a"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    InternalEdges:
    - Split: LeftToRight
      ReqOut:
        Dashes: one
      ReqIn:
        Or:
        - Dashes: two
        - Dashes: one
          Difficulty: hard
  - Room: "12b"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    InternalEdges:
    - Split: LeftToRight
      ReqBoth:
        Dashes: one
  - Room: "13"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
      ReqIn:
        Dashes: one
    - Side: Right
      Idx: 1
      Kind: inout
      ReqIn:
        Dashes: one
    - Side: Left
      Idx: 0
      Kind: in
      ReqIn:
        Dashes: one
    - Side: Left
      Idx: 1
      Kind: in
      ReqIn:
        Dashes: one
  - Room: "14a"  # TODO shorten jumpthru
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "14b"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Or:
        - Dashes: one
        - Dashes: zero
          Difficulty: hard
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "15"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 1
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: in
    - Side: Left
      Idx: 1
      Kind: in
  - Room: "16a"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    InternalEdges:
    - Split: LeftToRight
      ReqOut:
        Dashes: one
      ReqIn:
        Or:
        - Dashes: two
        - Dashes: one
          Difficulty: expert
  - Room: "16b"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "17"
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
    - Side: Left
      Idx: 1
      Kind: in
    InternalEdges:
    - To: "right"
      ReqBoth:
        Dashes: one
    Subrooms:
    - Room: "right"
      Holes:
      - Side: Right
        Idx: 0
        Kind: inout
      - Side: Right
        Idx: 1
        Kind: inout
  - Room: "18a"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    InternalEdges:
    - Split: LeftToRight
      ReqOut:
        Dashes: one
      ReqIn:
        Or:
        - Dashes: one
          Difficulty: expert
        - Dashes: two
          Difficulty: hard
  - Room: "18b"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    InternalEdges:
    - Split: LeftToRight
      ReqBoth:
        Dashes: one
  - Room: "19"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
      ReqOut:
        Dashes: one
    - Side: Left
      Idx: 0
      Kind: in
    - Side: Left
      Idx: 1
      Kind: in
  - Room: "20"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    InternalEdges:
    - Split: LeftToRight
      ReqBoth:
        Dashes: one
  - Room: "b-00"
    Holes:
    - Side: Up
      Idx: 1
      Kind: inout
      ReqOut:
        Dashes: one
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "b-00b"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
      ReqOut:
        Dashes: one
        Difficulty: hard
      ReqIn:
        Dashes: one
    - Side: Down
      Idx: 0
      Kind: inout
    - Side: Up
      Idx: 0
      Kind: In
  - Room: "b-00c"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
  - Room: "b-01"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
    InternalEdges:
    - Split: LeftToRight
      ReqOut:
        Dashes: zero
      ReqIn:
        Dashes: one
  - Room: "b-02"
    Holes:
    - Side: Up
      Idx: 0
      Kind: in
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
  - Room: "b-02b"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "b-03"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "boss-00"
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
    - Side: Down
      Idx: 0
      Kind: out
  - Room: "boss-01"
    Holes:
    - Side: Up
      Idx: 0
      Kind: in
    - Side: Down
      Idx: 0
      Kind: out
  - Room: "boss-02"
    Holes:
    - Side: Up
      Idx: 0
      Kind: in
    - Side: Down
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
  - Room: "boss-03"
    Holes:
    - Side: Up
      Idx: 0
      Kind: in
    - Side: Down
      Idx: 0
      Kind: out
  - Room: "boss-04"
    Holes:
    - Side: Up
      Idx: 0
      Kind: in
    - Side: Right
      Idx: 0
      Kind: out
  - Room: "boss-05"
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
    - Side: Down
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
  - Room: "boss-06"
    Holes:
    - Side: Up
      Idx: 0
      Kind: in
    - Side: Down
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
  - Room: "boss-07"
    Holes:
    - Side: Up
      Idx: 0
      Kind: in
    - Side: Down
      Idx: 0
      Kind: out
  - Room: "boss-08"
    Holes:
    - Side: Up
      Idx: 0
      Kind: in
    - Side: Down
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
  - Room: "boss-09"
    Holes:
    - Side: Up
      Idx: 0
      Kind: in
    - Side: Right
      Idx: 0
      Kind: out
  - Room: "boss-10"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "boss-11"
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
    - Side: Down
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
  - Room: "boss-12"
    Holes:
    - Side: Up
      Idx: 0
      Kind: in
    - Side: Down
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
  - Room: "boss-13"
    Holes:
    - Side: Up
      Idx: 0
      Kind: in
    - Side: Right
      Idx: 0
      Kind: out
  - Room: "boss-14"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "boss-15"
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
    - Side: Down
      Idx: 0
      Kind: out
  - Room: "boss-16"
    Holes:
    - Side: Up
      Idx: 0
      Kind: in
    - Side: Right
      Idx: 0
      Kind: out
  - Room: "boss-17"
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
    - Side: Down
      Idx: 0
      Kind: out
  - Room: "boss-18"
    Holes:
    - Side: Up
      Idx: 0
      Kind: in
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
  - Room: "boss-19"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "boss-20"
    Holes:
    - Side: Up
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: two
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "after-00"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
      ReqOut:
        Or:
        - Dashes: one
        - Dashes: zero
          Difficulty: hard
    - Side: Down
      Idx: 0
      Kind: in  # TODO shorten jumpthru
  - Room: "after-01"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
      ReqOut:
        Dashes: one
    - Side: Down
      Idx: 0
      Kind: in
  - Room: "after-02"
    Holes:
    - Side: Down
      Idx: 0
      Kind: in
    End: true

BSide:
  - Room: "a-00"
    Holes:
    - Side: Up
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
  - Room: "a-01"
    Holes:
    - Side: Up
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
    - Side: Down
      Idx: 0
      Kind: in
  - Room: "a-02"
    Holes:
    - Side: Up
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
    - Side: Down
      Idx: 0
      Kind: in
  - Room: "a-03"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
    - Side: Down
      Idx: 0
      Kind: in
  - Room: "a-04"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "a-05"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "a-06"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "b-00"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
    InternalEdges:
    - Split: LeftToRight
      ReqOut:
        Dashes: zero
      ReqIn:
        Dashes: one
  - Room: "b-01"
    Holes:
    - Side: Up
      Idx: 0
      Kind: in
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
  - Room: "b-02"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "b-03"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "b-04"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "b-05"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "b-06"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "b-07"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "b-08"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "b-10"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
      ReqOut:
        Dashes: one
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "c-00"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
    - Side: Left
      Idx: 0
      Kind: in
    - Side: Down
      Idx: 0
      Kind: None
    - Side: Down
      Idx: 1
      Kind: None
    - Side: Down
      Idx: 2
      Kind: None
    - Side: Down
      Idx: 3
      Kind: None
    - Side: Down
      Idx: 4
      Kind: None
  - Room: "c-01"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "c-02"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "c-03"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "c-04"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "d-00"
    Holes:
    - Side: Up
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "d-01"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
    - Side: Down
      Idx: 0
      Kind: in
  - Room: "d-02"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "d-03"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "d-04"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "d-05"
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
      ReqIn:
        Dashes: one
    End: true

CSide:
  - Room: "00"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
        Difficulty: hard
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "01"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "02"
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
      ReqIn:
        Dashes: one
    End: true
