ASide:
  - Room: "bridge"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "inside"
    Holes:
  - Room: "outside"
    Holes:
    - Side: Right
      Idx: 0
      Kind: none
    End: true
  - Room: "secret"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
