ASide:
  - Room: "intro-00-past"
    Holes:
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: None
  - Room: "intro-01-future"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
  - Room: "intro-02-launch"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
  - Room: "intro-03-space"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
  - Room: "a-00"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "a-01"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Up
      Idx: 0
      Kind: None
    - Side: Up
      Idx: 1
      Kind: None
  - Room: "a-02"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "a-03"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "a-04"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "a-05"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "b-00"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "b-01"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "b-02"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "b-03"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "b-04"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "b-05"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "b-06"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "b-07"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: in
    - Side: Up
      Idx: 0
      Kind: None
    - Side: Down
      Idx: 0
      Kind: None
  - Room: "c-00"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 1
      Kind: out
      # TODO: split right-1 into two holes to match strange ascent capability in farewell
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "c-00b"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "c-01"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "c-02"
    Holes:
    - Side: Up
      Idx: 1
      Kind: out
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "c-03"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: None
    - Side: Left
      Idx: 1
      Kind: in
    - Side: Down
      Idx: 0
      Kind: in
    - Side: Right
      Idx: 0
      Kind: None
  - Room: "c-alt-00"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Right
      Idx: 1
      Kind: none
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 1
      Kind: inout
  - Room: "c-alt-01"
    Holes:
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 1
      Kind: out
    - Side: Left
      Idx: 0
      Kind: in
    - Side: Left
      Idx: 1
      Kind: none
  - Room: "d-00"
    Holes:
    - Side: Up
      Idx: 0
      Kind: out
    - Side: Up
      Idx: 1
      Kind: out
    - Side: Up
      Idx: 2
      Kind: none
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Right
      Idx: 1
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: out
    - Side: Down
      Idx: 1
      Kind: in
  - Room: "d-01"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
  - Room: "d-02"
    Holes:
    - Side: Down
      Idx: 0
      Kind: inout
  - Room: "d-03"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "d-04"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "d-05"
    Holes:
    - Side: Up
      Idx: 0
      Kind: in
    - Side: Down
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 1
      Kind: in
  - Room: "e-00y"
    Holes:
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: in
    - Side: Up
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 0
      Kind: inout
      # TODO: split holes
    - Side: Left
      Idx: 0
      Kind: None
    - Side: Right
      Idx: 0
      Kind: None
  - Room: "e-00yb"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "e-00z"
    Holes:
    - Side: Up
      Idx: 1
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: in
    - Side: Down
      Idx: 2
      Kind: none
  - Room: "e-00"
    Holes:
    - Side: Up
      Idx: 0
      Kind: out
    - Side: Down
      Idx: 0
      Kind: in
  - Room: "e-00b"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 0
      Kind: None
    - Side: left
      Idx: 0
      Kind: None
    - Side: right
      Idx: 0
      Kind: None
  - Room: "e-01"
    Holes:
    - Side: Up
      Idx: 0
      Kind: out
    - Side: Down
      Idx: 0
      Kind: in
    - Side: Down
      Idx: 1
      Kind: none
  - Room: "e-02"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Down
      Idx: 0
      Kind: in
    - Side: Down
      Idx: 1
      Kind: None
  - Room: "e-03"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
  - Room: "e-03-dummy"
    Holes:
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 2
      Kind: none
  - Room: "e-04"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Left
      Idx: 0
      Kind: in
    - Side: down
      Idx: 0
      Kind: None
    - Side: down
      Idx: 1
      Kind: None
    - Side: down
      Idx: 2
      Kind: None
  - Room: "e-05"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "e-05b"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: none
  - Room: "e-05b-dummy"
    Holes:
    - Side: Up
      Idx: 0
      Kind: None
  - Room: "e-05c"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "e-06"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "e-07"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "e-08"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "f-door"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "f-00"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "f-01"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "f-02"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "f-03"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "f-04"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "f-05"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "f-06"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "f-07"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "f-08"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "f-09"
    Holes:
    - Side: Up
      Idx: 0
      Kind: out
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "g-00"
    Holes:
    - Side: Up
      Idx: 0
      Kind: out
    - Side: Down
      Idx: 0
      Kind: in
    - Side: left
      Idx: 0
      Kind: None
    - Side: right
      Idx: 0
      Kind: None
  - Room: "g-01"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: in
    - Side: Left
      Idx: 0
      Kind: None
    - Side: Right
      Idx: 0
      Kind: None
  - Room: "g-03"
    Holes:
    - Side: Up
      Idx: 0
      Kind: out
    - Side: Down
      Idx: 0
      Kind: in
  - Room: "g-02"
    Holes:
    - Side: Up
      Idx: 0
      Kind: out
    - Side: Down
      Idx: 0
      Kind: in
  - Room: "g-04"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Down
      Idx: 0
      Kind: in
  - Room: "g-05"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "g-06"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "h-00b"
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
    - Side: Down
      Idx: 0
      Kind: out
  - Room: "h-00"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: out
  - Room: "h-01"
    Holes:
    - Side: Up
      Idx: 0
      Kind: out
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "h-02"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Down
      Idx: 0
      Kind: in
  - Room: "h-03"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "h-03b"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "h-04"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Right
      Idx: 1
      Kind: out
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "h-04b"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: out
  - Room: "h-05"
    Holes:
    - Side: Up
      Idx: 0
      Kind: in
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "h-06"
    Holes:
    - Side: Up
      Idx: 0
      Kind: out
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "h-06b"
    Holes:
    - Side: Up
      Idx: 0
      Kind: out
    - Side: Down
      Idx: 0
      Kind: in
  - Room: "h-07"
    Holes:
    - Side: Left
      Idx: 0
      Kind: None
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Down
      Idx: 0
      Kind: in
  - Room: "h-08"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 1
      Kind: out
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "h-09"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Left
      Idx: 1
      Kind: inout
  - Room: "h-10"
    Holes:
    - Side: Up
      Idx: 0
      Kind: None # TODO: fix hole
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "i-00"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 1
      Kind: out
    - Side: Down
      Idx: 0
      Kind: in
  - Room: "i-00b"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 1
      Kind: in
  - Room: "i-01"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "i-02"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "i-03"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
  - Room: "i-04"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "i-05"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "j-00"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "j-00b"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "j-01"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "j-02"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Right
      Idx: 1
      Kind: none
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "j-03"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Left
      Idx: 0
      Kind: in
    - Side: Left
      Idx: 1
      Kind: none
  - Room: "j-04"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Right
      Idx: 1
      Kind: none
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "j-05"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Left
      Idx: 0
      Kind: in
    - Side: Left
      Idx: 1
      Kind: none
  - Room: "j-06"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "j-07"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: in  # TODO: remove no-exit restriction
  - Room: "j-08"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "j-09"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "j-10"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "j-11"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "j-12"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "j-13"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Right
      Idx: 1
      Kind: none
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "j-14"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Left
      Idx: 0
      Kind: in
    - Side: Left
      Idx: 1
      Kind: none
  - Room: "j-14b"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "j-15"
    Holes:
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "j-16"
    Holes:
    - Side: Up
      Idx: 0
      Kind: None
    - Side: Up
      Idx: 1
      Kind: out
    - Side: Up
      Idx: 2
      Kind: None
    - Side: Left
      Idx: 0
      Kind: in
  - Room: "j-17"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Up
      Idx: 1
      Kind: in
    - Side: Right
      Idx: 0
      Kind: out
    - Side: Down
      Idx: 0
      Kind: in
  - Room: "j-18"
    Holes:
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: in
    - Side: Down
      Idx: 1
      Kind: inout
  - Room: "j-19"
    Holes:
    - Side: Left
      Idx: 0
      Kind: None
    - Side: Left
      Idx: 1
      Kind: None
    - Side: Left
      Idx: 2
      Kind: in
    - Side: Right
      Idx: 0
      Kind: None
    - Side: Right
      Idx: 1
      Kind: None
    - Side: Right
      Idx: 2
      Kind: None
    - Side: Right
      Idx: 3
      Kind: None
  - Room: "end-cinematic"
    Holes:
  - Room: "end-golden"
    Holes:
  - Room: "end-granny"
    Holes:
